---

- name: Check existence of tandoor systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ tandoor_identifier }}.service"
  register: tandoor_service_stat

- when: tandoor_service_stat.stat.exists | bool
  block:
    - name: Ensure tandoor systemd service is stopped
      ansible.builtin.service:
        name: "{{ tandoor_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure tandoor systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ tandoor_identifier }}.service"
        state: absent

    - name: Ensure tandoor path doesn't exist
      ansible.builtin.file:
        path: "{{ tandoor_base_path }}"
        state: absent
